### PR TITLE
Fix issuers bug

### LINKED ISSUE #606: Missing issuers in GCP and AWS
This is likely caused by [this return statement](https://github.com/transparency-dev/tesseract/blob/42e6d0c6d93dbd1a3941902f33b0bea978850185/storage/gcp/issuers.go#L110), which really, should be a continue.

It's only impacting AWS and GCP, not POSIX.

Let's fix one of the TODO an use error groups + parallel writes while we're there.

### PR DESCRIPTION
**Pull request by AlCutter**
This PR fixes a couple of issues in the GCP and AWS issuer storage implementations:
- In certain conditions, it's possible that intermediates could be lost without any error being surfaced.
- A SEGV if an error is returned from the S3 client which isn't an instance of `smithy.APIError`.

Fixes #606

### CODE REVIEW

File: storage/aws/issuers.go [hunk 1]
```diff
@@ -83,6 +86,8 @@ func (s *IssuersStorage) keyToObjName(key []byte) string {
 
 // AddIssuers stores Issuers values under their Key if there isn't an object under Key already.
 func (s *IssuersStorage) AddIssuersIfNotExist(ctx context.Context, kv []storage.KV) error {
+	eg := errgroup.Group{}
+
 	// We first try and see if this issuer cert has already been stored since reads
```
Comment (phbnf) [inline storage/aws/issuers.go]: I think this is outdated or misplaced

**Review by phbnf — APPROVED** [review]
